### ISSUE TITLE
war3MapMap.blp from LostTemple.w3m corrupted

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [triggerhappy187/PHP-MPQ#10]
There is a problem with your MPQ reading procedure. When I use readFile on war3MapMap.blp of (4)LostTemple.w3m, it gets corrupted. I uploaded it to your demo database. See the problem there. Lots of pixels in the minimap are corrupted (violet and somehow wrong).

**Comment by cipherxof** [comment]
This has been fixed in https://github.com/triggerhappy187/PHP-MPQ/commit/7a2ae53c88e8c0a10072ae1ae88e7832e2994907. The reason the code was outputting an invalid image was because it was attempting to decompress an uncompressed sector. It's likely the sector was left uncompressed due to the data already being compressed in the JPEG-BLP image. 

I added a check to make sure the decompressed data is bigger than the sector data and it fixed the issue.
